import React, { useState, useEffect } from "react";
import api from "../api";

// Principal Signature Management Component
const PrincipalSignaturePanel = () => {
  const [signatureStatus, setSignatureStatus] = useState(null);
  const [loading, setLoading] = useState(true);
  const [uploading, setUploading] = useState(false);
  const [error, setError] = useState("");

  useEffect(() => {
    fetchSignatureStatus();
  }, []);

  const fetchSignatureStatus = async () => {
    try {
      setLoading(true);
      const response = await api.get("/admin/clubs/principal_signature/");
      setSignatureStatus(response.data);
    } catch (err) {
      setError("Failed to load signature status");
      console.error("Error loading principal signature:", err);
    } finally {
      setLoading(false);
    }
  };

  const handleFileUpload = async (event) => {
    const file = event.target.files[0];
    if (!file) return;

    // Validate file type
    if (!file.type.startsWith('image/')) {
      setError('Please select a valid image file');
      return;
    }

    // Validate file size (max 5MB)
    if (file.size > 5 * 1024 * 1024) {
      setError('File size must be less than 5MB');
      return;
    }

    setUploading(true);
    setError("");

    try {
      const formData = new FormData();
      formData.append('signature', file);

      const response = await api.post("/admin/clubs/principal_signature/", formData, {
        headers: {
          'Content-Type': 'multipart/form-data',
        },
      });

      setSignatureStatus(response.data);
      setError("");
    } catch (err) {
      setError(err.response?.data?.error || 'Failed to upload signature');
      console.error("Error uploading signature:", err);
    } finally {
      setUploading(false);
    }
  };

  if (loading) {
    return <div className="p-4 text-center">Loading signature status...</div>;
  }

  return (
    <div className="space-y-4">
      {error && (
        <div className="p-3 bg-red-100 border border-red-400 text-red-700 rounded">
          {error}
        </div>
      )}

      <div className="flex items-center justify-between p-4 bg-gray-50 rounded-lg">
        <div>
          <h3 className="text-lg font-semibold text-gray-800">
            Principal: {signatureStatus?.principal_name || 'Not Found'}
          </h3>
          <p className="text-sm text-gray-600">
            This signature will be used on certificates generated by clubs
          </p>
        </div>

        <div className="flex items-center gap-4">
          {signatureStatus?.has_signature ? (
            <div className="text-green-600 flex items-center gap-2">
              <span className="text-sm">✓ Signature Available</span>
              {signatureStatus.signature_url && (
                <img
                  src={signatureStatus.signature_url}
                  alt="Principal Signature"
                  className="h-12 w-auto border border-gray-300 rounded"
                />
              )}
            </div>
          ) : (
            <span className="text-red-600 text-sm">⚠ No signature uploaded</span>
          )}

          <label className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 cursor-pointer transition-colors">
            <input
              type="file"
              accept="image/*"
              onChange={handleFileUpload}
              disabled={uploading}
              className="hidden"
            />
            {uploading ? 'Uploading...' : (signatureStatus?.has_signature ? 'Update Signature' : 'Upload Signature')}
          </label>
        </div>
      </div>
    </div>
  );
};

const AdminClubManagement = () => {
    try {
      await api.post(`/admin/clubs/${clubId}/assign_club_head/`, {
        student_id: studentId,
      });
      setSuccess("Club head assigned successfully");
      fetchData();
    } catch {
      setError("Failed to assign club head");
    }
  };

  const handleAssignOrganizer = async (clubId, organizerId) => {
    try {
      await api.post(`/admin/clubs/${clubId}/assign_organizer/`, {
        organizer_id: organizerId,
      });
      setSuccess("Organizer assigned successfully");
      fetchData();
    } catch {
      setError("Failed to assign organizer");
    }
  };

  if (loading) return <div className="text-center py-10">Loading clubs...</div>;

  return (
    <div className="space-y-6">
      {/* Alerts */}
      {error && (
        <div className="p-4 bg-red-100 border border-red-400 text-red-700 rounded">
          {error}
        </div>
      )}
      {success && (
        <div className="p-4 bg-green-100 border border-green-400 text-green-700 rounded">
          {success}
        </div>
      )}

      {/* Create Club Button */}
      <div className="bg-white p-6 rounded-lg shadow">
        <button
          onClick={() => setShowCreateForm(!showCreateForm)}
          className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
        >
          ➕ Create Club
        </button>
      </div>

      {/* Create Club Form */}
      {showCreateForm && (
        <div className="bg-white p-6 rounded-lg shadow">
          <h3 className="text-lg font-bold mb-4">Create New Club</h3>

          <form onSubmit={handleCreateClub} className="space-y-4">
            <div>
              <label className="block text-sm font-medium">Club Name</label>
              <input
                type="text"
                value={formData.name}
                onChange={(e) =>
                  setFormData({ ...formData, name: e.target.value })
                }
                required
                className="w-full px-4 py-2 border rounded-lg"
              />
            </div>

            <div>
              <label className="block text-sm font-medium">
                Club Description
              </label>
              <textarea
                value={formData.description}
                onChange={(e) =>
                  setFormData({ ...formData, description: e.target.value })
                }
                className="w-full px-4 py-2 border rounded-lg"
                rows="4"
              ></textarea>
            </div>

            <div>
              <label className="block text-sm font-medium">
                Established Date
              </label>
              <input
                type="date"
                value={formData.established_date}
                onChange={(e) =>
                  setFormData({
                    ...formData,
                    established_date: e.target.value,
                  })
                }
                className="w-full px-4 py-2 border rounded-lg"
              />
            </div>

            <div>
              <label className="block text-sm font-medium">
                Faculty Coordinator (Optional)
              </label>
              <select
                value={formData.faculty_coordinator || ""}
                onChange={(e) =>
                  setFormData({
                    ...formData,
                    faculty_coordinator: e.target.value,
                  })
                }
                className="w-full px-4 py-2 border rounded-lg"
              >
                <option value="">Select Faculty Coordinator</option>
                {mentors.map((mentor) => (
                  <option key={mentor.id} value={mentor.id}>
                    {mentor.user_details?.first_name}{" "}
                    {mentor.user_details?.last_name}
                  </option>
                ))}
              </select>
            </div>

            <div className="flex gap-4">
              <button
                type="submit"
                className="px-6 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700"
              >
                Create Club
              </button>
              <button
                type="button"
                onClick={() => setShowCreateForm(false)}
                className="px-6 py-2 bg-gray-400 text-white rounded-lg hover:bg-gray-500"
              >
                Cancel
              </button>
            </div>
          </form>
        </div>
      )}

      {/* Principal Signature Management */}
      <div className="bg-white p-6 rounded-lg shadow">
        <h2 className="text-xl font-bold mb-4 text-gray-800">
          Principal Signature
        </h2>
        <PrincipalSignaturePanel />
      </div>

      {/* Clubs List */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {clubs.map((club) => (
          <div key={club.id} className="bg-white p-6 rounded-lg shadow">
            <h3 className="text-xl font-bold mb-2">{club.name}</h3>
            <p className="text-gray-600 mb-4">{club.description}</p>

            <div className="space-y-4">
              {/* Faculty Coordinator */}
              <div>
                <label className="text-sm font-medium text-gray-700">
                  Faculty Coordinator
                </label>
                <select
                  value={club.faculty_coordinator || ""}
                  onChange={(e) =>
                    handleAssignCoordinator(club.id, e.target.value)
                  }
                  className="w-full px-3 py-2 border rounded"
                >
                  <option value="">Select Mentor</option>
                  {mentors.map((mentor) => (
                    <option key={mentor.id} value={mentor.id}>
                      {mentor.user_details?.first_name}{" "}
                      {mentor.user_details?.last_name}
                    </option>
                  ))}
                </select>
              </div>

              {/* Club Head */}
              <div>
                <label className="text-sm font-medium text-gray-700">
                  Club Head
                </label>
                <select
                  value={club.club_head || ""}
                  onChange={(e) => handleAssignHead(club.id, e.target.value)}
                  className="w-full px-3 py-2 border rounded"
                >
                  <option value="">Select Student</option>
                  {students.map((student) => (
                    <option key={student.id} value={student.id}>
                      {student.user_details?.first_name}{" "}
                      {student.user_details?.last_name}
                    </option>
                  ))}
                </select>
              </div>

              {/* Assign Organizer */}
              <div>
                <label className="text-sm font-medium text-gray-700">
                  Assign Organizer
                </label>
                <select
                  // value={club.club_head || ""}
                  defaultValue=""
                  onChange={(e) => {
                    if (e.target.value) {
                      handleAssignOrganizer(club.id, e.target.value);
                      e.target.value = "";
                    }
                  }}
                  className="w-full px-3 py-2 border rounded"
                >
                  <option value="">Select Organizer</option>
                  {organizers.map((org) => (
                    <option key={org.id} value={org.id}>
                      {org.user_details?.first_name}
                      {org.user_details?.last_name}
                    </option>
                  ))}
                </select>

                {/* Show current organizers */}
                <div className="mt-2">
                  <p className="text-sm font-medium">Current Organizers:</p>
                  {club.organizers && club.organizers.length > 0 ? (
                    <ul className="text-sm list-disc ml-4">
                      {club.organizers.map((org) => (
                        <li key={org.id}>
                          {org.user?.first_name ||
                            org.user_details?.first_name ||
                            ""}{" "}
                          {org.user?.last_name ||
                            org.user_details?.last_name ||
                            ""}
                        </li>
                      ))}
                    </ul>
                  ) : (
                    <p className="text-sm text-gray-500">
                      No organizers assigned
                    </p>
                  )}
                </div>
              </div>

              {/* Additional Info */}
              <div className="text-sm text-gray-600">
                <p>👥 Members: {club.members?.length || 0}</p>
                <p>📅 Established: {club.established_date || "N/A"}</p>
                <p>
                  Status:{" "}
                  <span
                    className={`px-2 py-1 rounded text-xs ${
                      club.is_active
                        ? "bg-green-100 text-green-800"
                        : "bg-red-100 text-red-800"
                    }`}
                  >
                    {club.is_active ? "Active" : "Inactive"}
                  </span>
                </p>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default AdminClubManagement;
